### ISSUE TITLE
建议增加点任务

### ISSUE THREAD

**Issue by xu8117** [move-cn/letsmove#800]
再增加点任务吧，没奖励的也行。通过任务学习比看视频和文档效率高

**Comment by rickiey** [comment]
这个建议不错,主要给个学习的方向,目前项目种类太少,照抄模仿的项目都不多,建议开discussions,让大家可以自己发表一些想法/任务

**Comment by uvd** [comment]
discussions  已经开了 多增加任务 我也在想  社区还是有不少人在好好学习的 主要教程我们也还在完善
